#!/bin/sh

DIR=$2

player="${DIR}/sample_player"
coach="${DIR}/sample_coach"
teamname="TWINTEAM"
host=$1
port=6000

config="${DIR}/player.conf"
config_dir="${DIR}/formations-dt"
coach_config="${DIR}/coach.conf"

savior="on"

if [ $savior = "on" ] ; then
  savior="--savior on "
fi

if [ X"${coach_port}" = X'' ]; then
  coach_port=`expr ${port} + 2`
fi

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${host} -p ${port} -t ${teamname}"
opt="${opt} ${savior}"

$player ${opt} -g &
sleep 3

$player ${opt} &
sleep 1

$player ${opt} &
sleep 1

$player ${opt} &
sleep 1

$player ${opt} &
sleep 1

$player ${opt} &
sleep 1

wait
